# ==========================================
# Global Conflict & Economic Impact Analysis
# Phase 1: Data Loading & Cleaning
# ==========================================

In [ ]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)

In [ ]:
conflict_df = pd.read_csv('Conflict.csv')

print("Shape :", conflict_df.shape)

conflict_df.head()

Shape : (2816, 28)

,conflict_id,location,side_a,side_a_id,side_a_2nd,side_b,side_b_id,side_b_2nd,incompatibility,territory_name,year,intensity_level,cumulative_intensity,type_of_conflict,start_date,start_prec,start_date2,start_prec2,ep_end,ep_end_date,ep_end_prec,gwno_a,gwno_a_2nd,gwno_b,gwno_b_2nd,gwno_loc,region,version
0,200,Bolivia,Government of Bolivia,23,NaN,Popular Revolutionary Movement,719,NaN,2,NaN,1946,2,1,3,1946-07-18,1,1946-07-21,2,1,1946-07-21,NaN,145,NaN,NaN,NaN,145,5,26.1
1,200,Bolivia,Government of Bolivia,23,NaN,MNR,720,NaN,2,NaN,1949,1,1,3,1946-07-18,1,1949-09-15,3,1,1949-09-15,NaN,145,NaN,NaN,NaN,145,5,26.1
2,200,Bolivia,Government of Bolivia,23,NaN,MNR,720,NaN,2,NaN,1952,1,1,3,1946-07-18,1,1952-04-09,1,1,1952-04-12,NaN,145,NaN,NaN,NaN,145,5,26.1
3,200,Bolivia,Government of Bolivia,23,NaN,ELN,721,NaN,2,NaN,1967,1,1,3,1946-07-18,1,1967-03-31,3,1,1967-10-16,NaN,145,NaN,NaN,NaN,145,5,26.1
4,201,Cambodia (Kampuchea),Government of France,33,NaN,Khmer Issarak,160,NaN,1,Cambodia,1946,1,0,1,1946-08-31,3,1946-08-31,3,0,NaN,NaN,220,NaN,NaN,NaN,811,3,26.1

In [ ]:
military_df = pd.read_csv(
    'Military_Spending.csv',
    skiprows=4
)

print("Shape :", military_df.shape)

military_df.head()

Shape : (266, 71)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,Military expenditure (current USD),MS.MIL.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Military expenditure (current USD),MS.MIL.XPND.CD,NaN,NaN,NaN,3.219951e+08,4.398005e+08,5.239918e+08,5.631079e+08,5.992006e+08,6.518399e+08,7.481927e+08,8.080516e+08,9.305694e+08,9.784166e+08,1.341007e+09,1.912090e+09,2.359066e+09,2.711217e+09,3.516242e+09,4.436187e+09,5.059938e+09,5.688876e+09,5.821777e+09,5.586491e+09,5.954550e+09,6.059015e+09,5.268639e+09,5.815940e+09,7.253047e+09,8.315636e+09,8.403082e+09,9.777790e+09,8.341007e+09,6.310707e+09,7.129497e+09,5.621953e+09,5.084816e+09,4.478141e+09,4.739305e+09,4.137541e+09,5.722503e+09,5.401733e+09,4.488594e+09,4.895651e+09,5.646539e+09,7.366020e+09,8.391802e+09,1.016898e+10,1.123301e+10,1.354834e+10,1.353461e+10,1.193966e+10,1.324343e+10,1.383986e+10,1.558198e+10,1.682935e+10,1.538332e+10,1.365941e+10,1.617268e+10,1.227049e+10,1.169172e+10,1.144376e+10,1.253894e+10,1.322901e+10,1.373257e+10,1.365905e+10,NaN,NaN
2,Afghanistan,AFG,Military expenditure (current USD),MS.MIL.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.939586e+06,NaN,NaN,3.341272e+06,3.581366e+06,4.203665e+06,5.393251e+06,6.127288e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.251116e+08,1.227272e+08,1.313462e+08,2.195802e+08,2.405326e+08,2.518695e+08,2.981471e+08,3.258069e+08,2.385834e+08,2.171941e+08,2.682388e+08,1.995171e+08,1.858783e+08,1.914071e+08,1.980747e+08,2.263062e+08,2.795770e+08,2.782508e+08,NaN,NaN,NaN,NaN,NaN
3,Africa Western and Central,AFW,Military expenditure (current USD),MS.MIL.XPND.CD,NaN,6.573052e+07,9.002825e+07,1.005711e+08,1.188867e+08,1.456340e+08,1.507266e+08,2.794051e+08,4.680855e+08,7.921951e+08,8.057568e+08,7.984013e+08,1.073660e+09,1.225931e+09,1.569425e+09,3.325926e+09,2.972064e+09,3.538129e+09,3.531859e+09,3.749098e+09,3.819500e+09,2.995896e+09,2.333428e+09,2.271656e+09,1.833692e+09,1.782806e+09,1.325887e+09,1.034039e+09,1.028974e+09,8.696224e+08,1.058239e+09,1.017904e+09,1.121450e+09,1.223171e+09,8.894220e+08,1.114381e+09,1.243017e+09,1.365594e+09,1.630291e+09,1.034573e+09,9.593010e+08,1.269265e+09,1.677374e+09,1.793043e+09,1.955987e+09,2.015580e+09,2.343547e+09,2.945811e+09,4.420055e+09,4.304860e+09,4.658214e+09,4.987983e+09,4.921502e+09,6.171135e+09,6.451565e+09,5.016333e+09,5.575535e+09,5.510401e+09,6.325122e+09,6.163842e+09,7.196958e+09,9.713964e+09,8.502193e+09,9.427717e+09,8.015683e+09,NaN,NaN
4,Angola,AGO,Military expenditure (current USD),MS.MIL.XPND.CD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.432716e+08,5.047129e+08,4.973594e+08,6.188916e+08,6.684939e+08,7.786283e+08,1.066248e+09,1.146467e+09,1.156494e+09,1.487399e+09,1.469383e+09,1.948559e+09,1.751153e+09,1.031248e+09,7.941388e+08,1.774398e+09,5.949912e+08,2.338437e+08,1.597419e+08,4.567805e+08,1.702783e+08,1.066589e+09,5.836213e+08,4.042991e+08,4.386862e+08,6.700212e+08,8.175336e+08,1.365055e+09,1.970309e+09,2.032433e+09,3.163591e+09,3.311193e+09,3.500795e+09,3.639496e+09,4.144635e+09,6.090752e+09,6.846249e+09,3.608299e+09,2.764055e+09,3.062873e+09,1.983614e+09,1.470939e+09,9.935944e+08,9.814510e+08,1.622764e+09,1.247846e+09,9.220508e+08,NaN,NaN

In [ ]:
inflation_df = pd.read_csv(
    'Inflation.csv',
    skiprows=4
)

print("Shape :", inflation_df.shape)

inflation_df.head()

Shape : (266, 71)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.032258,1.073966,3.643045,3.121868,3.991628,5.836688,5.555556,3.873375,5.215560,6.311080,3.361391,3.225288,2.999948,1.869489,2.280372,4.044021,2.883604,3.315247,3.656365,2.529129,3.397787,3.608024,5.392568,8.955987,-2.135429,2.078141,4.316297,0.627472,-2.372065,0.421441,0.474764,-0.931196,-1.028282,3.626041,4.257462,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.598394,15.224099,11.216481,14.238055,12.526893,15.06985,15.066512,14.461591,12.139918,11.567524,10.983863,13.006566,13.891972,12.563443,12.522258,12.558202,12.457914,17.678100,16.167612,13.135661,14.852815,12.288591,9.706586,10.249599,7.495255,7.819865,8.601485,5.840354,8.763755,7.449700,5.023421,8.558038,8.898164,8.450775,12.566645,8.954218,5.537538,8.971206,9.158708,5.748831,5.525819,5.098562,6.446877,6.221375,4.689806,4.102851,5.191629,6.824727,10.883478,7.399186,4.770857,NaN,NaN
2,Afghanistan,AFG,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.686269,6.784597,8.680571,26.418664,-6.811161,2.178538,11.804186,6.441213,7.385772,4.673996,-0.661709,4.383892,4.975952,0.626149,2.302373,5.601888,5.133203,13.712102,-4.644709,-6.601186,NaN,NaN
3,Africa Western and Central,AFW,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.799211,12.059765,10.671937,11.250000,7.354926,5.950965,0.248789,2.523659,0.869287,1.057361,1.741888,-0.062999,0.553456,31.841017,10.563289,4.914240,3.997142,4.471125,0.372266,2.530775,4.361529,3.188693,1.760904,0.694336,5.631634,4.415900,3.607368,8.452976,3.282440,1.784844,4.018699,4.578375,2.439201,1.768436,2.130817,1.487416,1.725486,1.784050,1.983092,2.490378,3.745568,7.949251,5.221168,3.608044,NaN,NaN
4,Angola,AGO,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.783784,299.509804,1378.527607,949.792531,2666.450593,4145.105982,219.176721,107.284822,248.195902,324.996872,152.561022,108.897436,98.224144,43.542107,22.953514,13.305210,12.251497,12.475829,13.730284,14.469656,13.482468,10.277905,8.777814,7.280387,9.355972,30.694415,29.844480,19.628938,17.080954,22.271539,25.754295,21.355290,13.644102,28.240495,NaN,NaN

In [ ]:
oil_df = pd.read_csv('Oil_Data.csv')

print("Shape :", oil_df.shape)

oil_df.head()

Shape : (10553, 2)

  observation_date  DCOILWTICO
0       1986-01-02       25.56
1       1986-01-03       26.00
2       1986-01-06       26.53
3       1986-01-07       25.85
4       1986-01-08       25.87

In [ ]:
conflict_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2816 entries, 0 to 2815
Data columns (total 28 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   conflict_id           2816 non-null   int64
 1   location              2816 non-null   object
 2   side_a                2816 non-null   object
 3   side_a_id             2816 non-null   object
 4   side_a_2nd            479 non-null    object
 5   side_b                2816 non-null   object
 6   side_b_id             2816 non-null   object
 7   side_b_2nd            147 non-null    object
 8   incompatibility       2816 non-null   int64
 9   territory_name        1586 non-null   object
 10  year                  2816 non-null   int64
 11  intensity_level       2816 non-null   int64
 12  cumulative_intensity  2816 non-null   int64
 13  type_of_conflict      2816 non-null   int64
 14  start_date            2816 non-null   object
 15  start_prec            2816 non-null   int64
 16  start_date2           2816 non-null   object
 17  start_prec2           2816 non-null   int64
 18  ep_end                2816 non-null   int64
 19  ep_end_date           563 non-null    object
 20  ep_end_prec           0 non-null      float64
 21  gwno_a                2816 non-null   object
 22  gwno_a_2nd            479 non-null    object
 23  gwno_b                155 non-null    object
 24  gwno_b_2nd            147 non-null    object
 25  gwno_loc              2816 non-null   object
 26  region                2816 non-null   object
 27  version               2816 non-null   float64
dtypes: float64(2), int64(9), object(17)
memory usage: 616.1+ KB

In [ ]:
conflict_df.isnull().sum().sort_values(ascending=False)

ep_end_prec    2816
side_b_2nd     2669
gwno_b_2nd     2669
gwno_b         2661
gwno_a_2nd     2337
               ...
start_prec        0
gwno_a            0
gwno_loc          0
region            0
version           0
Length: 28, dtype: int64

In [ ]:
conflict_df.columns.tolist()

['conflict_id',
 'location',
 'side_a',
 'side_a_id',
 'side_a_2nd',
 'side_b',
 'side_b_id',
 'side_b_2nd',
 'incompatibility',
 'territory_name',
 'year',
 'intensity_level',
 'cumulative_intensity',
 'type_of_conflict',
 'start_date',
 'start_prec',
 'start_date2',
 'start_prec2',
 'ep_end',
 'ep_end_date',
 'ep_end_prec',
 'gwno_a',
 'gwno_a_2nd',
 'gwno_b',
 'gwno_b_2nd',
 'gwno_loc',
 'region',
 'version']

In [ ]:
conflict_df = conflict_df.drop_duplicates()

print("Shape After Removing Duplicates")

conflict_df.shape

Shape After Removing Duplicates

(2816, 28)

In [ ]:
military_df.columns.tolist()

['Country Name',
 'Country Code',
 'Indicator Name',
 'Indicator Code',
 '1960',
 '1961',
 '1962',
 '1963',
 '1964',
 '1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '1970',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022',
 '2023',
 '2024',
 '2025',
 'Unnamed: 70']

In [ ]:
keep_cols = ['Country Name','Country Code']

for year in range(2000,2025):
    keep_cols.append(str(year))

military_df = military_df[keep_cols]

military_df.head()

,Country Name,Country Code,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,5.401733e+09,4.488594e+09,4.895651e+09,5.646539e+09,7.366020e+09,8.391802e+09,1.016898e+10,1.123301e+10,1.354834e+10,1.353461e+10,1.193966e+10,1.324343e+10,1.383986e+10,1.558198e+10,1.682935e+10,1.538332e+10,1.365941e+10,1.617268e+10,1.227049e+10,1.169172e+10,1.144376e+10,1.253894e+10,1.322901e+10,1.373257e+10,1.365905e+10
2,Afghanistan,AFG,NaN,NaN,NaN,NaN,1.251116e+08,1.227272e+08,1.313462e+08,2.195802e+08,2.405326e+08,2.518695e+08,2.981471e+08,3.258069e+08,2.385834e+08,2.171941e+08,2.682388e+08,1.995171e+08,1.858783e+08,1.914071e+08,1.980747e+08,2.263062e+08,2.795770e+08,2.782508e+08,NaN,NaN,NaN
3,Africa Western and Central,AFW,9.593010e+08,1.269265e+09,1.677374e+09,1.793043e+09,1.955987e+09,2.015580e+09,2.343547e+09,2.945811e+09,4.420055e+09,4.304860e+09,4.658214e+09,4.987983e+09,4.921502e+09,6.171135e+09,6.451565e+09,5.016333e+09,5.575535e+09,5.510401e+09,6.325122e+09,6.163842e+09,7.196958e+09,9.713964e+09,8.502193e+09,9.427717e+09,8.015683e+09
4,Angola,AGO,5.836213e+08,4.042991e+08,4.386862e+08,6.700212e+08,8.175336e+08,1.365055e+09,1.970309e+09,2.032433e+09,3.163591e+09,3.311193e+09,3.500795e+09,3.639496e+09,4.144635e+09,6.090752e+09,6.846249e+09,3.608299e+09,2.764055e+09,3.062873e+09,1.983614e+09,1.470939e+09,9.935944e+08,9.814510e+08,1.622764e+09,1.247846e+09,9.220508e+08

In [ ]:
military_df.isnull().sum().sort_values(
    ascending=False
).head(20)

2000    74
2001    73
2002    70
2024    70
2011    69
2023    68
2007    67
2009    67
2010    67
2020    67
2019    67
2022    67
2015    66
2006    66
2021    66
2017    65
2003    65
2016    65
2012    65
2004    64
dtype: int64

In [ ]:
military_df = military_df.fillna(method='ffill', axis=1)

military_df.head()

/tmp/ipykernel_4980/154964360.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  military_df = military_df.fillna(method='ffill', axis=1)

,Country Name,Country Code,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,ABW,ABW,ABW,ABW,ABW,ABW,ABW,ABW,ABW,ABW,ABW,ABW,ABW,ABW,ABW,ABW,ABW,ABW,ABW,ABW,ABW,ABW,ABW,ABW,ABW
1,Africa Eastern and Southern,AFE,5401733241.50712,4488594404.40717,4895651489.67202,5646539416.27222,7366020357.18671,8391802332.31698,10168981008.6831,11233010788.2932,13548342318.6203,13534612775.636499,11939662796.339899,13243429787.974501,13839864655.026501,15581977215.053699,16829353040.2181,15383318097.650801,13659413872.3535,16172675472.106899,12270486684.636,11691723928.9498,11443761587.064199,12538942807.1952,13229012881.3545,13732573540.4478,13659048840.316601
2,Afghanistan,AFG,AFG,AFG,AFG,AFG,125111557.457054,122727193.134874,131346231.269517,219580214.296198,240532594.620985,251869514.820335,298147102.825701,325806949.72333,238583385.374322,217194107.113298,268238787.719988,199517108.764826,185878310.062383,191407113.244397,198074728.574408,226306243.729258,279576954.925193,278250788.014927,278250788.014927,278250788.014927,278250788.014927
3,Africa Western and Central,AFW,959300982.609088,1269265105.71866,1677374103.82213,1793043312.25745,1955986947.41056,2015580275.88297,2343547220.22438,2945810821.62647,4420055281.36649,4304860294.26092,4658214435.30059,4987982651.04179,4921502460.77794,6171135414.06019,6451564749.92889,5016333439.14496,5575535214.60029,5510400667.6926,6325121729.78858,6163842037.42304,7196957645.04129,9713964207.414749,8502192591.61574,9427716905.99577,8015682860.17091
4,Angola,AGO,583621333.598924,404299139.990661,438686245.411232,670021164.432494,817533582.152083,1365055398.69044,1970309115.18376,2032432883.4343,3163591147.40902,3311193245.27722,3500794836.44649,3639496373.5446,4144634851.46856,6090751702.00884,6846249313.34052,3608299114.61674,2764054937.15976,3062872913.9838,1983613748.00089,1470938717.28754,993594404.625879,981451011.871799,1622763731.95097,1247846345.08517,922050813.886942

In [ ]:
military_long = military_df.melt(
    id_vars=['Country Name','Country Code'],
    var_name='Year',
    value_name='Military_Spending'
)

military_long.head()

                  Country Name Country Code  Year Military_Spending
0                        Aruba          ABW  2000               ABW
1  Africa Eastern and Southern          AFE  2000  5401733241.50712
2                  Afghanistan          AFG  2000               AFG
3   Africa Western and Central          AFW  2000  959300982.609088
4                       Angola          AGO  2000  583621333.598924

In [ ]:
inflation_df.columns.tolist()

['Country Name',
 'Country Code',
 'Indicator Name',
 'Indicator Code',
 '1960',
 '1961',
 '1962',
 '1963',
 '1964',
 '1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '1970',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022',
 '2023',
 '2024',
 '2025',
 'Unnamed: 70']

In [ ]:
keep_cols = ['Country Name','Country Code']

for year in range(2000,2025):
    keep_cols.append(str(year))

inflation_df = inflation_df[keep_cols]

inflation_df.head()

,Country Name,Country Code,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,4.044021,2.883604,3.315247,3.656365,2.529129,3.397787,3.608024,5.392568,8.955987,-2.135429,2.078141,4.316297,0.627472,-2.372065,0.421441,0.474764,-0.931196,-1.028282,3.626041,4.257462,NaN,NaN,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,8.601485,5.840354,8.763755,7.449700,5.023421,8.558038,8.898164,8.450775,12.566645,8.954218,5.537538,8.971206,9.158708,5.748831,5.525819,5.098562,6.446877,6.221375,4.689806,4.102851,5.191629,6.824727,10.883478,7.399186,4.770857
2,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,12.686269,6.784597,8.680571,26.418664,-6.811161,2.178538,11.804186,6.441213,7.385772,4.673996,-0.661709,4.383892,4.975952,0.626149,2.302373,5.601888,5.133203,13.712102,-4.644709,-6.601186
3,Africa Western and Central,AFW,2.530775,4.361529,3.188693,1.760904,0.694336,5.631634,4.415900,3.607368,8.452976,3.282440,1.784844,4.018699,4.578375,2.439201,1.768436,2.130817,1.487416,1.725486,1.784050,1.983092,2.490378,3.745568,7.949251,5.221168,3.608044
4,Angola,AGO,324.996872,152.561022,108.897436,98.224144,43.542107,22.953514,13.305210,12.251497,12.475829,13.730284,14.469656,13.482468,10.277905,8.777814,7.280387,9.355972,30.694415,29.844480,19.628938,17.080954,22.271539,25.754295,21.355290,13.644102,28.240495

In [ ]:
inflation_long = inflation_df.melt(
    id_vars=['Country Name','Country Code'],
    var_name='Year',
    value_name='Inflation_Rate'
)

inflation_long.head()

                  Country Name Country Code  Year  Inflation_Rate
0                        Aruba          ABW  2000        4.044021
1  Africa Eastern and Southern          AFE  2000        8.601485
2                  Afghanistan          AFG  2000             NaN
3   Africa Western and Central          AFW  2000        2.530775
4                       Angola          AGO  2000      324.996872

In [ ]:
oil_df.columns

Index(['observation_date', 'DCOILWTICO'], dtype='object')

In [ ]:
oil_df['observation_date'] = pd.to_datetime(
    oil_df['observation_date']
)

oil_df.head()

  observation_date  DCOILWTICO
0       1986-01-02       25.56
1       1986-01-03       26.00
2       1986-01-06       26.53
3       1986-01-07       25.85
4       1986-01-08       25.87

In [ ]:
oil_df['Year'] = oil_df['observation_date'].dt.year

oil_df.head()

  observation_date  DCOILWTICO  Year
0       1986-01-02       25.56  1986
1       1986-01-03       26.00  1986
2       1986-01-06       26.53  1986
3       1986-01-07       25.85  1986
4       1986-01-08       25.87  1986

In [ ]:
oil_df['DCOILWTICO'] = pd.to_numeric(
    oil_df['DCOILWTICO'],
    errors='coerce'
)

In [ ]:
oil_yearly = oil_df.groupby('Year')['DCOILWTICO'].mean().reset_index()

oil_yearly.rename(
    columns={'DCOILWTICO':'Average_Oil_Price'},
    inplace=True
)

oil_yearly.head()

   Year  Average_Oil_Price
0  1986          15.047689
1  1987          19.200512
2  1988          15.965409
3  1989          19.635486
4  1990          24.526576

In [ ]:
military_long['Year'] = military_long['Year'].astype(int)

inflation_long['Year'] = inflation_long['Year'].astype(int)

conflict_df['year'] = conflict_df['year'].astype(int)

In [ ]:
print("Conflict Dataset :", conflict_df.shape)

print("Military Dataset :", military_long.shape)

print("Inflation Dataset :", inflation_long.shape)

print("Oil Dataset :", oil_yearly.shape)

Conflict Dataset : (2816, 28)
Military Dataset : (6650, 4)
Inflation Dataset : (6650, 4)
Oil Dataset : (41, 2)

In [ ]:
conflict_df.to_csv(
    'clean_conflict.csv',
    index=False
)

military_long.to_csv(
    'clean_military.csv',
    index=False
)

inflation_long.to_csv(
    'clean_inflation.csv',
    index=False
)

oil_yearly.to_csv(
    'clean_oil.csv',
    index=False
)

print("All Cleaned Files Saved")

All Cleaned Files Saved